### ISSUE TITLE
Provide values for alarm in JSON /data

### ISSUE THREAD

**Issue by DutchmanNL** [Phantomias2006/Nemesis#96]
It would be useful to receive alerts when the min or max temperature has been reached (same as in the Webinterface).
This would allow easy processing of additional events ( like messaging or lighting) without additional scripting to trigger the event.

Wanted feature for ioBroker implementation : https://github.com/iobroker-community-adapters/ioBroker.wlanthermo-nano/issues/1

**Comment by DutchmanNL** [comment]
any idea if this will be considered ?

**Comment by sochs** [comment]
Principally possible, but the information is already in the JSON, by comparison from the current to the min/max temperature. There is no acknowledgment of the alarm in JSON, so when should the alarm stop? That's why we didn't include that in the JSON. Therefore, an alarm should be generated where it can also be reset.

**Comment by DutchmanNL** [comment]
Discussed with end-user of wanted integration we will close this feature request.
Alarm states, confirmation etc should be handled within the iOT solution not the source that makes sense
